@include('layout.includedfiles.metatags')
@include('layout.includedfiles.navbar')
@include('layout.includedfiles.header')
@include('layout.includedfiles.mainContent')
@include('layout.includedfiles.footer')
