no1 = int(input("Enter first number : "))
no2 = int(input("Enter second number : "))
print("Addition\t :\t ",(no1+no2))
print("Subtraction\t :\t ",(no1-no2))
print("Multiplication\t :\t ",(no1*no2))
print("Division\t :\t ",(no1/no2))
print("Modulo\t\t :\t ",(no1%no2))
